 version: "2"
 services:
   application:
     labels:
       com.microsoft.acs.dcos.marathon.vhost: "etherciszekunagents.westeurope.cloudapp.azure.com"
     build: ./application
     # Name image
     image: ethercis-app
     # Map application container port 8080 to Docker port 8080
     ports:
       - "8080:8080"
     # Do not start application container until postgres service is started
     depends_on:
       - postgres

   postgres:
     # Build database using Dockerfile contained in postgres subfolder
     build: ./postgres
     # Name image
     image: ethercis-db
